### ISSUE TITLE
MPLS tunnel not work

### ISSUE THREAD

**Issue by yan43029** [i-maravic/MPLS-Linux#10]
Thanks for the source code for MPLS, there are 2 questions to ask:

(1) Does this kernel support VPLS?

(2) the MPLS tunnel command (ip link add tunnel type mpls) does not work
We have tried using the following commands to build the MPLS tunnel. The tunnel is successfully created, however, when PE1 pings to PE2, the receiver PE2 can only receive the MPLS packets but no reply to PE1. For ip route add command, it works, but we would like to use the ip link add tunnel command.

PE1(192.168.44.100) -----------> PE2(192.168.44.101)
( using eth1 to be the base of MPLS tunnel, name of the tunnel: mpls2, MPLS label: 1001, pop label: 2001)

On PE1:
ip link set mpls0 up
ip link set eth1 mpls on
ip link add mpls2 type mpls push 1001 dev eth1 192.168.44.101
ifconfig mpls2 192.168.44.100 netmask 255.255.255.0 up
ip -M route add 2001 mpls pop 1

We have configured PE2 similarly. Is there anything missing or  wrong command to pop out the label?

Thank you and highly appreciate.

**Comment by solaris7** [comment]
I am trying to set this up as well. Were you able to get this working both ways?

Solaris

**Comment by dannftk** [comment]
actually, I faced exactly the same issue. I was up it almost a day debugging using KGDB and tracing function by function and step by step even looking into the commands of assembler. Finally, I found out that the deal was in Reverse Path Filtering feature of Linux kernel. You might have encountered the same problem.
I have the following scheme configured:

[LEFT CER, 1.1.1.1/24]<--ETH|IP|ICMP-->[1.1.1.2/24, LEFT LER, 10.0.0.1/8]<--ETH|MPLS|IP|ICMP-->[10.0.0.2/8, MIDDLE LSR, 11.0.0.1/8]<--ETH|MPLS|IP|ICMP-->[11.0.0.2/8. RIGHT LER, 2.2.2.1/24]<--ETH|IP|ICMP-->[2.2.2.2/24, RIGHT CER]
There are routes on LEFT CER and RIGHT CER to send IP packets to each other using the interfaces connected to LERs of MPLS subnetwork. MPLS LERs and swapping-LSR in the middle work the way they are supposed to be, nothing changed

Supposing we sent an ICMP packet from the LEFT CER to the RIGHT CER 
On the host RIGHT LER we pop the MPLS label out and then get a normal IP packet again. Now it is left to send it out via the interface connected to RIGHT CER. The RPF feature on the RIGHT LER host prevents a packet to pass the normal fib_lookup for the source IP address of the original packet going from LEFT CER. It occurs because RIGHT CER does not have any IP addresses alike the source address. This causes Linux to ignore the packet and drop it

Here the clause of describing the RPF feature: http://tldp.org/HOWTO/Adv-Routing-HOWTO/lartc.kernel.rpf.html

So, my decision was very simple and direct. I turned off the feature throughout and replies started flowing:
for iface in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > $iface; done
